set_property PACKAGE_PIN E3 [get_ports CLK]
set_property PACKAGE_PIN M17 [get_ports RESET]
set_property PACKAGE_PIN R15 [get_ports char4[3]]
set_property PACKAGE_PIN M13 [get_ports char4[2]]
set_property PACKAGE_PIN L16 [get_ports char4[1]]
set_property PACKAGE_PIN J15 [get_ports char4[0]]

set_property PACKAGE_PIN R13 [get_ports char3[3]]
set_property PACKAGE_PIN U18 [get_ports char3[2]]
set_property PACKAGE_PIN T18 [get_ports char3[1]]
set_property PACKAGE_PIN R17 [get_ports char3[0]]

set_property PACKAGE_PIN T13 [get_ports char2[3]]
set_property PACKAGE_PIN R16 [get_ports char2[2]]
set_property PACKAGE_PIN U8 [get_ports char2[1]]
set_property PACKAGE_PIN T8 [get_ports char2[0]]

set_property PACKAGE_PIN V10 [get_ports char1[3]]
set_property PACKAGE_PIN U11 [get_ports char1[2]]
set_property PACKAGE_PIN U12 [get_ports char1[1]]
set_property PACKAGE_PIN H6 [get_ports char1[0]]

set_property PACKAGE_PIN T10 [get_ports LED[7]]
set_property PACKAGE_PIN R10 [get_ports LED[6]]
set_property PACKAGE_PIN K16 [get_ports LED[5]]
set_property PACKAGE_PIN K13 [get_ports LED[4]]
set_property PACKAGE_PIN P15 [get_ports LED[3]]
set_property PACKAGE_PIN T11 [get_ports LED[2]]
set_property PACKAGE_PIN L18 [get_ports LED[1]]
set_property PACKAGE_PIN H15 [get_ports LED[0]]

set_property PACKAGE_PIN U13 [get_ports AN0]
set_property PACKAGE_PIN K2 [get_ports AN1]
set_property PACKAGE_PIN T14 [get_ports AN2]
set_property PACKAGE_PIN P14 [get_ports AN3]
set_property PACKAGE_PIN J14 [get_ports AN4]
set_property PACKAGE_PIN T9 [get_ports AN5]
set_property PACKAGE_PIN J18 [get_ports AN6]
set_property PACKAGE_PIN J17 [get_ports AN7]


set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports char1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports char1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports char1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports char1[3]]

set_property IOSTANDARD LVCMOS33 [get_ports char2[0]]
set_property IOSTANDARD LVCMOS33 [get_ports char2[1]]
set_property IOSTANDARD LVCMOS33 [get_ports char2[2]]
set_property IOSTANDARD LVCMOS33 [get_ports char2[3]]

set_property IOSTANDARD LVCMOS33 [get_ports char3[0]]
set_property IOSTANDARD LVCMOS33 [get_ports char3[1]]
set_property IOSTANDARD LVCMOS33 [get_ports char3[2]]
set_property IOSTANDARD LVCMOS33 [get_ports char3[3]]

set_property IOSTANDARD LVCMOS33 [get_ports char4[0]]
set_property IOSTANDARD LVCMOS33 [get_ports char4[1]]
set_property IOSTANDARD LVCMOS33 [get_ports char4[2]]
set_property IOSTANDARD LVCMOS33 [get_ports char4[3]]

set_property IOSTANDARD LVCMOS33 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[7]]

set_property IOSTANDARD LVCMOS33 [get_ports AN0]
set_property IOSTANDARD LVCMOS33 [get_ports AN1]
set_property IOSTANDARD LVCMOS33 [get_ports AN2]
set_property IOSTANDARD LVCMOS33 [get_ports AN3]
set_property IOSTANDARD LVCMOS33 [get_ports AN4]
set_property IOSTANDARD LVCMOS33 [get_ports AN5]
set_property IOSTANDARD LVCMOS33 [get_ports AN6]
set_property IOSTANDARD LVCMOS33 [get_ports AN7]